sdcrud/SDCRUD/urls.py
from django.contrib import admin
from django.urls import path, include
from App import views 

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('reset_password', views.reset_password, name='reset'), 
    
    path('', views.listarAcoes),  
    path('adicionar',views.adicionar),  
    path('editar/<int:id>', views.editar),  
    path('atualizar/<int:id>', views.atualizar),  
    path('remover/<int:id>', views.remover),

    path('api/v1/', include('api.urls', namespace='api')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

sdcrud/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 

urlpatterns = [
    path('register/', views.SignUp.as_view(), name = "signup"), 
    ]

sdcrud/api/urls.py
from rest_framework.routers import DefaultRouter
from api.views import AcaoViewSet

app_name = 'api'

router = DefaultRouter(trailing_slash=False)
router.register(r'acoes', AcaoViewSet)

urlpatterns = router.urls

sdcrud/App/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import Permission
# Create your models here.

class CustomPermissions:
    CAN_CRUD_DATA = 'can_crud_data'

    @staticmethod
    def initialize():
        # Cria as permissões personalizadas caso ainda não existam
        Permission.objects.get_or_create(
            codename=CustomPermissions.CAN_CRUD_DATA,
            name='Can Create, Edit, and Delete Data',
        )

class Acao(models.Model):  
    #ser = models.ForeignKey(settings.AUTH_USER_MODEL, null=False, blank=False, on_delete=models.CASCADE)
    id = models.AutoField(primary_key=True, null=False)
    codigo_acao = models.CharField(max_length=10, blank=False, null=False)  
    descricao = models.TextField(max_length=200)
    data = models.DateField()
    open = models.DecimalField(max_digits=6, decimal_places=2, blank=False, null=False)
    close = models.DecimalField(max_digits=6, decimal_places=2,blank=False, null=False)
    high = models.DecimalField(max_digits=6, decimal_places=2,blank=False, null=False)
    low = models.DecimalField(max_digits=6, decimal_places=2,blank=False, null=False)
    volume = models.IntegerField(blank=False, null=False, default=0)

sdcrud/accounts/models.py
from django.db import models

# Create your models here.

sdcrud/api/models.py
from django.db import models

# Create your models here.

class Acao(models.Model):  
    id = models.AutoField(primary_key=True, null=False)
    codigo_acao = models.CharField(max_length=10, blank=False, null=False)  
    descricao = models.TextField(max_length=200)
    data = models.DateField()
    open = models.DecimalField(max_digits=6, decimal_places=2, blank=False, null=False)
    close = models.DecimalField(max_digits=6, decimal_places=2,blank=False, null=False)
    high = models.DecimalField(max_digits=6, decimal_places=2,blank=False, null=False)
    low = models.DecimalField(max_digits=6, decimal_places=2,blank=False, null=False)
    volume = models.IntegerField(blank=False, null=False, default=0)

sdcrud/App/views.py
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model,update_session_auth_hash
from django.shortcuts import render, redirect   
from App.models import Acao  
from App.formulario import AcaoFormulario

User = get_user_model()

def reset_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('/')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'registration/reset_password.html', {'form': form})

@permission_required('App.can_crud_data')
def adicionar(request):  
    if request.method == "POST":  
        form = AcaoFormulario(request.POST)  
        if form.is_valid():  
            try: 
                form.instance.user = request.user
                form.save() 
                return redirect('/')  
            except:  
                pass 
    else:  
        form = AcaoFormulario()  
    return render(request,'adicionar.html',{'form':form}) 


@login_required()
def listarAcoes(request):  
    lista_acoes = Acao.objects.all()
    return render(request,"listar.html",{'lista_acoes':lista_acoes})  

@permission_required('App.can_crud_data')
def editar(request, id):  
    acao = Acao.objects.get(id=id) 
    return render(request,'editar.html', {'acao':acao})  

@permission_required('App.can_crud_data')
def atualizar(request, id):  
    acao = Acao.objects.get(id=id)

    form = AcaoFormulario(request.POST, instance=acao)  
    if form.is_valid():
        try:
            form.instance.user = request.user
            form.save()  
            return redirect('/')
        except ValueError:
            print(ValueError)
            
    else: 
        return render(request, 'editar.html', {'acao':acao}) 
 
@permission_required('App.can_crud_data')
def remover(request, id):  
    acao = Acao.objects.get(id=id)  
    acao.delete()  
    return redirect("/")  

sdcrud/accounts/views.py
from django.shortcuts import render

from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/register.html'

sdcrud/api/views.py
# from django.shortcuts import render
from api.serializers import AcaoSerializer
from rest_framework import viewsets, permissions
from App.models import Acao
from api.serializers import AcaoSerializer

class AcaoViewSet(viewsets.ModelViewSet):
    queryset = Acao.objects.all()
    serializer_class = AcaoSerializer
    permission_classes = [permissions.IsAuthenticated]

sdcrud/App/templates/adicionar.html
{% extends "base.html" %}

{% block title %}Adicionar nova Ação{% endblock title %}

{% block content %}
<div class="col-md-6 m-auto">
 
  <!-- formulário -->
  <form method="POST" class="post-form" action="/adicionar">  
    {% csrf_token %}  
    <div class="container my-4 ">
      <div class="bg-light py-3 border">  
  
        <div class="form-group row mb-2 d-flex flex-column align-content-center">  
          <div class="col-sm-10 text-center"><h3>Adicionar</h3></div>  
        </div>  

        <div class="form-group row mb-2 justify-content-center">  
          <label class="col-sm-4 col-form-label">Código Ação:</label>  
          <div class="col-sm-4">  
            {{ form.codigo_acao }}  
          </div>  
        </div> 

        <div class="form-group row mb-2 justify-content-center">  
          <label class="col-sm-4 col-form-label">Descrição:</label>  
          <div class="col-sm-4">  
            {{ form.descricao }}  
          </div>  
        </div>  

        <div class="form-group row mb-2 justify-content-center">  
          <label class="col-sm-4 col-form-label">Data:</label>  
          <div class="col-sm-4">  
            {{ form.data }}  
          </div>  
        </div>  

        <div class="form-group row mb-2 justify-content-center">  
          <label class="col-sm-4 col-form-label">Open:</label>  
          <div class="col-sm-4">  
            {{ form.open}}  
          </div>  
        </div> 

        <div class="form-group row mb-2 justify-content-center">  
          <label class="col-sm-4 col-form-label">Close:</label>  
          <div class="col-sm-4">  
            {{ form.close }}  
          </div>  
        </div> 

        <div class="form-group row mb-2 justify-content-center">  
          <label class="col-sm-4 col-form-label">High:</label>  
          <div class="col-sm-4">  
            {{ form.high }}  
          </div>  
        </div> 

        <div class="form-group row mb-2 justify-content-center">  
          <label class="col-sm-4 col-form-label">Low:</label>  
          <div class="col-sm-4">  
            {{ form.low }}  
          </div>  
        </div> 

        <div class="form-group row  justify-content-center">  
          <label class="col-sm-4 col-form-label">Volume:</label>  
          <div class="col-sm-4">  
            {{ form.volume }}  
          </div>  
        </div> 

        <div class="form-group row  justify-content-center">   
          <div class="col-sm-8 mt-3">  
            <button type="submit" class="btn btn-success w-100 rounded-0 ">Enviar</button>  
          </div>  
        </div>

      </div>
    </div>
  </form>  
</div> 
{% endblock content %} 

sdcrud/App/templates/base.html
<!DOCTYPE html>  
<html lang="pt-br">  
<head>  
   <meta charset="UTF-8">  
   <title>{% block title %}{% endblock %}</title>

   {% load static %}  

   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
   <link rel="stylesheet" href="{% static  'css/custom.css' %}">

</head> 
<body>
   
   <header class="bg-success py-2 text-white">
      <nav class="navbar px-5">
         <h4 class="text-center">B3Track</h4> 
         <ul class="navbar-nav mr-auto d-flex flex-row gap-4">
            {% if user.is_authenticated %}
            <li class="nav-item">
               <a class='nav-link text-white' href="/">Home</a>
            </li>
            <li class="nav-item">
               <a class='nav-link text-white' href="/reset_password">Change Password</a>
            </li>
            {% else %}
            <li class="nav-item">
               <a class='nav-link text-white' href="/accounts/login">Entrar</a>
            </li>
            {% endif %}
            {% if user.is_authenticated %}
            <li class="nav-item">
               <a class='nav-link text-white' href="/accounts/logout">Sair</a>
            </li>
            {% endif%}

         </ul>
      </nav>
   </header>
   <div class="container-fluid px-5">
      <div class="row">
         {% block content %}
            <!-- conteudo aqui -->
         {% endblock %}
      </div>
   </div>
   <script src="{% static 'js/custom.js' %}"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
   <script src="//code.jquery.com/jquery-3.5.1.js"></script>
   <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
   <script src="//cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
   <script>
      $(document).ready(function() {
         $('#lista_acoes').DataTable({ "aLengthMenu": [[5, 10], [5, 10, "All"]], "iDisplayLength": 5});
      });
   </script>
</body> 
</html>

sdcrud/App/templates/editar.html
{% extends "base.html" %}

{% block title %}Editar Ação{% endblock title %}

{% block content %}
<div class="col-md-6 m-auto">
  <!-- Formulario de edição  -->
  <form method="POST" class="post-form" action="/atualizar/{{acao.id}}">  
    {% csrf_token %}  
    <div class="container my-4"> 
      <div class="bg-light  py-3 border">  
        <!-- titulo da pagina -->
        <div class="form-group row mb-2 d-flex flex-column align-content-center">   
          <div class="col-sm-10 text-center"><h3>Detalhes da Atualização</h3></div>  
        </div> 

        <!-- codigo da acao -->
        <div class="form-group row mb-2  justify-content-center">  
          <label class="col-sm-4 col-form-label">Código Ação:</label>  
          <div class="col-sm-4">  
            <input type="text" class="form-control w-100" name="codigo_acao" id="id_codigo_acao" required maxlength="10" value="{{ acao.codigo_acao }}" />  
          </div>  
        </div>
        <!-- descrição da Ação  -->
        <div class="form-group row mb-2 justify-content-center">  
          <label class="col-sm-4 col-form-label">Descrição:</label>  
          <div class="col-sm-4">  
            <input type="text" class="form-control" name="descricao" id="id_descricao" required maxlength="150" value="{{ acao.descricao }}" />  
          </div>
        </div> 
        <!--Data da Açao  -->
        <div class="form-group row mb-2 justify-content-center">  
          <label class="col-sm-4 col-form-label">Data:</label>  
          <div class="col-sm-4">  
            <input type="text" class="form-control" name="data" id="id_data" required value="{{ acao.data|date:'d/m/Y' }}" />  
          </div>  
        </div>
        <!-- valor de abertura -->
        <div class="form-group row mb-2 justify-content-center">  
          <label class="col-sm-4 col-form-label">Open:</label>  
          <div class="col-sm-4">  
            <input type="text" class="form-control data-convert" name="open" id="id_open" required value="{{ acao.open}}"/>  
          </div>  
        </div> 
        <!-- Valor de fechamento -->
        <div class="form-group row mb-2 justify-content-center">  
          <label class="col-sm-4 col-form-label">Close:</label>  
          <div class="col-sm-4">  
            <input type="text" class="form-control data-convert" name="close" id="id_close" required value="{{ acao.close }}" />  
          </div>  
        </div> 
        <!-- maior alta do dia -->
        <div class="form-group row mb-2 justify-content-center">  
          <label class="col-sm-4 col-form-label">High:</label>  
          <div class="col-sm-4">  
            <input type="text" class="form-control data-convert" name="high" id="id_high" required value="{{ acao.high }}"/>  
          </div>  
        </div>
        <!-- Maior baixa do dia -->
        <div class="form-group row mb-2 justify-content-center">  
          <label class="col-sm-4 col-form-label">Low:</label>  
          <div class="col-sm-4">  
            <input type="text" class="form-control data-convert" name="low" id="id_low" required value="{{ acao.low }}" />  
          </div>  
        </div>
        <!-- Quantidade de ações vendidas -->
        <div class="form-group row mb-2 justify-content-center">  
          <label class="col-sm-4 col-form-label">Volume:</label>  
          <div class="col-sm-4">  
            <input type="text" class="form-control" name="volume" id="id_volume" required value="{{ acao.volume }}"/>  
          </div>  
        </div> 
        <!-- Botao salvar edição -->
        <div class="form-group row justify-content-center">  
          <div class="col-sm-8  mt-3">  
            <button type="submit" class="btn btn-success btn-lg w-100 rounded-0 ">Atualizar</button>  
          </div>  
        </div> 
      </div>
    </div>  
  </form>
</div>  
{% endblock content %} 

sdcrud/App/templates/listar.html
{% extends "base.html" %}
 
{% block title %}Ações{% endblock title %}
 
{% block content %}
<div class="col-md-12 py-3">
    {% if user.is_superuser %}
        <span><a href="/adicionar" class="btn btn-success rounded-0 ">Adicionar Ação</a></span>  
    {% endif %}
    <div class="table-responsive">
        <table id="lista_acoes" class="table table-striped table-bordered" width="100%">
            <thead>
                <th><input type="checkbox" id="marcar-todas" /></th>
                <th>ID</th>
                <th>Codigo da Ação</th>
                <th>Descrição</th>
                <th>Data</th>
                <th>Open</th>
                <th>Close</th>
                <th>High</th>
                <th>Low</th>
                <th>Volume</th>
                {% if user.is_superuser %}
                <th>Editar</th>
                <th>Apagar</th>
                {% endif %}
            </thead>
            <tbody>
                {% for acao in lista_acoes %}  
                {% load static %}
                <tr>  
                    <td><input type="checkbox" class="marcar"/></td>
                    <td>{{ acao.id }}</td>  
                    <td>{{ acao.codigo_acao }}</td>  
                    <td>{{ acao.descricao }}</td>  
                    <td>{{ acao.data | date:'d-m-Y' }}</td>  
                    <td>{{ acao.open}}</td>
                    <td>{{ acao.close}}</td>
                    <td>{{ acao.high}}</td>
                    <td>{{ acao.low}}</td>
                    <td>{{ acao.volume}}</td>
                    {% if user.is_superuser %}
                    <td class="text-center">
                        <p data-placement="top" data-toggle="tooltip" title="Editar">
                            <a href="/editar/{{ acao.id }}" class="btn btn-primary btn-sm px-3" data-title="Editar" data-toggle="modal" data-target="#editar" >
                                <img src="{% static '/img/pencil.svg' %}">
                            </a>
                        </p>
                    </td>
                    <td class="text-center">
                        <p data-placement="top" data-toggle="tooltip" title="Deletar">
                            <a href="/remover/{{ acao.id }}" class="btn btn-danger btn-sm px-3" data-title="Remover" data-toggle="modal" data-target="#remover" >
                                <img src="{% static '/img/trash.svg' %}">
                            </a>
                        </p>
                    </td> 
                    {% endif %} 
                </tr>  
                {% endfor %} 
            </tbody>         
        </table>
    </div>
</div>
{% endblock content %}